// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Api.Data;

namespace Web_Api.Migrations
{
    [DbContext(typeof(FacturaContext))]
    [Migration("20200324214801_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web_Api.Models.Almacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ciudad_Almacen");

                    b.Property<string>("Nombre_Almacen");

                    b.Property<int>("Telefono_Almacen");

                    b.HasKey("Id");

                    b.ToTable("Almacenes");
                });

            modelBuilder.Entity("Web_Api.Models.Almacen_Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad_Almacen_Producto");

                    b.Property<DateTime>("Fecha_Almacen_Producto");

                    b.Property<int>("Id_Almacen");

                    b.Property<int>("Id_Producto");

                    b.HasKey("Id");

                    b.ToTable("Almacenes_Productos");
                });

            modelBuilder.Entity("Web_Api.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cedula_Empleado");

                    b.Property<string>("Contra_Empleado");

                    b.Property<DateTime>("Fecha_Nac_Empleado");

                    b.Property<int>("Id_Fk_Sucursal");

                    b.Property<int>("Nombre_Empleado");

                    b.Property<int>("Sexo_Empleado");

                    b.Property<int>("Telefono_Empleado");

                    b.Property<string>("Usuario_Empleado");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Web_Api.Models.Empleado_Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha_Empleado_Producto");

                    b.Property<int>("Id_Empleado");

                    b.Property<int>("Id_Producto");

                    b.HasKey("Id");

                    b.ToTable("Empleados_Productos");
                });

            modelBuilder.Entity("Web_Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad");

                    b.Property<DateTime>("Fecha_Venc_Producto");

                    b.Property<string>("Nombre_Producto");

                    b.Property<double>("Precio_Producto");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Web_Api.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ciudad_Sucursal");

                    b.Property<string>("Nombre_Sucursal");

                    b.Property<int>("Telefono_Sucursal");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Web_Api.Models.Sucursal_Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad_Sucursal_Producto");

                    b.Property<DateTime>("Fecha_Sucursal_Producto");

                    b.Property<int>("Id_Producto");

                    b.Property<int>("Id_Sucursal");

                    b.HasKey("Id");

                    b.ToTable("Sucursales_Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
