// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Api.Data;

namespace Web_Api.Migrations
{
    [DbContext(typeof(FacturaContext))]
    [Migration("20200328044923_borrar")]
    partial class borrar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web_Api.Models.Almacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ciudad_Almacen");

                    b.Property<string>("Nombre_Almacen");

                    b.Property<string>("Telefono_Almacen");

                    b.HasKey("Id");

                    b.ToTable("Almacenes");
                });

            modelBuilder.Entity("Web_Api.Models.Almacen_Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cantidad_Almacen_Producto");

                    b.Property<string>("Fecha_Almacen_Producto");

                    b.Property<string>("Id_Almacen");

                    b.Property<string>("Id_Producto");

                    b.HasKey("Id");

                    b.ToTable("Almacenes_Productos");
                });

            modelBuilder.Entity("Web_Api.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cedula_Empleado");

                    b.Property<string>("Fecha_Nac_Empleado");

                    b.Property<string>("Id_Fk_Sucursal");

                    b.Property<string>("Nombre_Empleado");

                    b.Property<string>("Sexo_Empleado");

                    b.Property<string>("Telefono_Empleado");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Web_Api.Models.Empleado_Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cantidad_Empleado_Producto");

                    b.Property<string>("Id_Empleado");

                    b.Property<string>("Id_Producto");

                    b.HasKey("Id");

                    b.ToTable("Empleados_Productos");
                });

            modelBuilder.Entity("Web_Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Fecha_Venc_Producto");

                    b.Property<string>("Nombre_Producto");

                    b.Property<string>("Precio_Producto");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Web_Api.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ciudad_Sucursal");

                    b.Property<string>("Nombre_Sucursal");

                    b.Property<string>("Telefono_Sucursal");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Web_Api.Models.Sucursal_Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cantidad_Sucursal_Producto");

                    b.Property<string>("Fecha_Sucursal_Producto");

                    b.Property<string>("Id_Producto");

                    b.Property<string>("Id_Sucursal");

                    b.HasKey("Id");

                    b.ToTable("Sucursales_Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
